site_name: 'XDHealthCheck'
site_description: 'Documentation for PowerShell Module: XDHealthCheck'
site_author: 'Pierre Smit'
site_url: 'https://smitpi.github.io/XDHealthCheck'
 
repo_url: 'https://github.com/smitpi/XDHealthCheck'
repo_name:  'smitpi/XDHealthCheck'
 
copyright: '(c) 2019 Pierre Smit. All rights reserved.'
 
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github-square
      link: 'https://smitpi.github.io/XDHealthCheck'
 
markdown_extensions:
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
 
theme:
  name: material
  features:
    - navigation.instant
  language: en
  favicon: 'https://mentorshipmovement.co.za/wp-content/uploads/2019/09/linkedin-profilepic-400x400.png'
  logo: 'https://mentorshipmovement.co.za/wp-content/uploads/2019/09/linkedin-profilepic-400x400.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      accent: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: indigo
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
